dropdown_1/dropdown_1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls'))
]

dropdown_1/student/urls.py
from django.urls import path
from .views import CreateStudent,load_state,load_city

urlpatterns=[
    path('',CreateStudent.as_view(),name='create_student'),
    path('ajax_load_state',load_state,name='ajax_load_state'),
    path('ajax_load_city',load_city,name='ajax_load_city'),
]


dropdown_1/student/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    country_name=models.CharField(max_length=30)

    def __str__(self):
        return self.country_name

class State(models.Model):
    country_name=models.ForeignKey(Country,on_delete=models.CASCADE)
    state_name=models.CharField(max_length=30)

    def __str__(self):
        return self.state_name

class City(models.Model):
    state_name=models.ForeignKey(State,on_delete=models.CASCADE)
    city_name=models.CharField(max_length=30)

    def __str__(self):
        return self.city_name


class Student(models.Model):
    name=models.CharField(max_length=30)
    country=models.ForeignKey(Country,on_delete=models.CASCADE)
    state=models.ForeignKey(State,on_delete=models.CASCADE)
    city=models.ForeignKey(City,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


dropdown_1/student/forms.py
from django import forms
from .models import Student,City,State

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        #fields = '__all__'
        exclude = ['name',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['state'].queryset=State.objects.none()
        self.fields['city'].queryset = City.objects.none()


dropdown_1/student/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .models import Student,State,City
from .forms import StudentForm

# Create your views here.

class CreateStudent(CreateView):
    model = Student
    form_class = StudentForm
    template_name = 'student/create_student.html'

def load_state(request):
    country_id = request.GET.get('country')
    states = State.objects.filter(country_name_id=country_id)
    return render(request, 'student/state_dropdown.html', {'states': states})

def load_city(request):
    state_id = request.GET.get('state')
    cities = City.objects.filter(state_name_id=state_id)
    return render(request, 'student/city_dropdown.html', {'cities': cities})




dropdown_1/templates/student/city_dropdown.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.city_name }}</option>
{% endfor %}

dropdown_1/templates/student/create_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" id="createForm" state-url="{% url 'ajax_load_state' %}" city-url= "{% url 'ajax_load_city' %}">
  {% csrf_token %}
  {{form.as_table}}
  <button type="submit">Submit</button>
</form>
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
  <script>
    $("#id_country").change(function () {
      var url = $("#createForm").attr("state-url");
      var countryId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'country': countryId
        },
        success: function (data) {
          $("#id_state").html(data);
        }
      });

    });
    $("#id_state").change(function () {
      var url = $("#createForm").attr("city-url");
      var stateId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'state': stateId
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });
  </script>
</body>
</html>

dropdown_1/templates/student/state_dropdown.html
<option value="">---------</option>
{% for state in states %}
<option value="{{ state.pk }}">{{ state.state_name }}</option>
{% endfor %}